// Prioritized list of ~500 high-quality tickers, roughly ordered by market cap,
// covering the S&P 500, top-cap names, and frequently searched stocks.
// The cron handler uses this list to gradually seed missing stocks and keep
// the database growing automatically.
export const DEFAULT_TICKERS = [
  "MSFT","AAPL","AMZN","META","AVGO","GOOGL","TSLA","GOOG","BRK-B","JPM",
  "LLY","V","NFLX","XOM","ORCL","MA","WMT","JNJ","COST","ABBV",
  "HD","PLTR","PG","UNH","BAC","GE","CVX","WFC","IBM","AMD",
  "PM","CSCO","ABT","GS","KO","RTX","CAT","LIN","MCD","CRM",
  "MRK","DIS","UBER","T","PEP","NOW","INTU","MS","MU","TMO",
  "QCOM","APP","BKNG","LRCX","C","GEV","TXN","VZ","SCHW","BA",
  "AMAT","BLK","AXP","TJX","ISRG","NEE","ACN","SPGI","AMGN","APH",
  "ADBE","ANET","ETN","PFE","PGR","BSX","KLAC","LOW","UNP","GILD",
  "COF","PANW","HON","INTC","DHR","SYK","BX","MDT","ADI","WELL",
  "ADP","COP","DE","LMT","CRWD","CMCSA","MO","HOOD","TMUS","CB",
  "PLD","SO","CEG","VRTX","MMC","CME","ICE","SBUX","DUK","MCK",
  "PH","CDNS","CVS","TT","NEM","DASH","BMY","ORLY","SNPS","AMT",
  "WM","NOC","KKR","MSTR","RBLX","NKE","MMM","GD","MDLZ","CRH",
  "AJG","HWM","RCL","PNC","SHW","WMB","CI","BK","EQIX","MSI",
  "USB","TDG","EMR","AON","ELV","COIN","MRVL","MCO","ITW","JCI",
  "AZO","CTAS","FI","ECL","HCA","ADSK","SNOW","NSC","VST","CSX",
  "TEL","CL","PYPL","NET","GLW","TRV","PWR","URI","UPS","EOG",
  "HLT","APD","AEP","ALNY","AFL","DLR","TFC","SRE","MPC","ZTS",
  "CMI","SPG","GM","VRT","COR","LHX","ALL","MAR","FCX","FAST",
  "REGN","O","PSX","FTNT","APO","BDX","ROP","AXON","KMI","VLO",
  "CMG","WDAY","D","PCAR","SLB","IDXX","EA","STX","FDX","ROST",
  "CVNA","LNG","CARR","BKR","XEL","CBRE","ABNB","F","RSG","MET",
  "AMP","CTVA","DDOG","MNST","WBD","OKE","NDAQ","EW","PSA","DHI",
  "EXC","WCN","TTWO","FLUT","FERG","VEEV","AIG","AME","DELL","GWW",
  "CCI","YUM","MPWR","MSCI","WDC","ETR","EBAY","KMB","PAYX","TGT",
  "VMC","GRMN","KR","RMD","SYY","ROK","CPRT","MLM","HIG","CAH",
  "DAL","WEC","PRU","A","ED","TRGP","XYL","OTIS","CSGP","VRSK",
  "OXY","MCHP","FIS","WAB","FICO","EQT","WTW","KDP","IR","ARES",
  "CTSH","DD","GEHC","PCG","HPE","ACGL","EFX","VTR","VICI","UAL",
  "NRG","HUM","STT","KVUE","RJF","MTB","IQV","INSM","CCL","ZS",
  "TSCO","SOFI","KEYS","IRM","EXR","NUE","FITB","FIX","IBKR","EME",
  "ADM","AWK","AEE","BR","RDDT","HSY","AVB","TDY","ATO","GIS",
  "FANG","LYV","ODFL","LPLA","TEAM","SYF","DXCM","ES","BRO","PPL",
  "PHM","ALAB","PSTG","CBOE","HPQ","CNP","MTD","EXPE","HBAN","FE",
  "VLTO","DTE","CINF","ULTA","IP","NTRS","CHTR","STE","PTC","SMCI",
  "LEN","LDOS","WSM","MDB","LH","PPG","TPR","RF","EQR","VRSN",
  "HUBS","MKL","NTAP","HUBB","DOV","DG","K","TYL","TROW","FSLR",
  "DVN","SW","DRI","JBL","RKLB","CMS","TER","NVR","WRB","TTD",
  "PODD","CFG","KHC","CHD","CRDO","DGX","EIX","NTRA","CASY","CDW",
  "SBAC","CIEN","BIIB","CW","KEY","NI","ON","RBA","ZM","PKG",
  "ZBH","STLD","TRMB","TLN","LULU","CPAY","GWRE","GPC","STZ","GDDY",
  "UTHR","IT","NTNX","WST","HAL","APTV","DLTR","EL","AFRM","FFIV",
  "SSNC","PFG","PINS","TPL","PNR","SNA","THC","J","WY","WAT",
  "BE","TOST","DKNG","CNC","EVRG","LNT","USFD","ACM","ESS","FTAI",
  "CTRA","ROL","INVH","MKC","BWXT","COHR","LUV","LII","LVS","EXPD",
  "FTV","L","MAA","TRU","PFGC","DOW","FTI","SUI","BURL","FCNCA",
  "NVT","CG","IFF","OMC","GEN","FNF","IONQ","OKTA","KTOS","TSN",
  "GPN","EQH","ALLE","WWD","ZBRA","RPM","DECK","CLX","TXT","HOLX",
  "KIM","CHRW","RS","WPC","MAS","EWBC","EG","DT","DOCU","CF",
  "XPO","ARE","BBY","DKS","WSO","INCY","JLL","CSL","ENTG","GGG",
  "NBIX","ITT","ILMN","TWLO","BALL","COO","COOP","TOL","MTZ","RIVN",
  "DOC","Z","RGLD","TKO","REG","DPZ","ROKU","FN","NWSA","OKLO",
  "LECO","TW","NLY","APG","EHC","BLDR","U","AVY","RGA","LYB",
  "FOXA","UNM","GLPI","OHI","MANH","EVR","UDR","BJ","RBC","BAH",
  "IEX","DUOL","SNX","RNR","OC","AVAV","BXP","BAX","HST","CRS",
  "MEDP","VTRS","RL","NDSN","DTM","SWK","FHN","CDE","CPT","SWKS",
  "BG","HII","CCK","ATI","RMBS","CLH","HLI","NCLH","WTRG","SCI",
  "SJM","SF","TXRH","GME","BLD","CACI","GL","MOS","AIZ","UHS",
  "JKHY","AKAM","PAYC","FDS","WMS","SOLV","LITE","ALLY","SFM","PNW",
  "MLI","ELS","LAMR","OWL","EXEL","AYI","HIMS","POOL","AMH","JBHT",
  "NXT","CELH","BMRN","MOH","EXAS","AFG","DAY","OVV","WCC","IPG",
  "IVZ","CNM","RVTY","AGNC","MP","SATS","HAS","IOT","ARMK","LSCC",
  "WYNN","SSB","ELAN","ENSG","IONS","ASTS","AIT","AR","STRL","GNRC",
  "WBS","REXR","RBRK","ALB","RRX","DCI","BWA","KNSL","JEF","ORI",
  "PEN","AES","SEIC","OGE","FYBR","CUBE","RGTI","WAL","EGP","PR",
  "MRNA","PRI","DOCS","GTLS","CR","BBIO","W","IDCC","CNH","WTFC",
  "NYT","CMA","CRBG","ATR","SPXC","TTEK","CAG","FRT","PLNT","APA",
  "TECH","ALGN","HALO","AA","RRC","FIVE","AVTR","MTCH","BRX","QRVO",
  "AWI","AOS","NFG","DINO","ZION","SNAP","MKSI","CVLT","LYFT","JOBY",
  "OSK",
];

// Prioritized ticker list used by the background cron — the first ~500
// entries of DEFAULT_TICKERS, which are roughly ordered by market cap and
// represent the S&P 500 + top-cap + frequently searched names.
export const PRIORITIZED_TICKERS: string[] = DEFAULT_TICKERS.slice(0, 500);

